### PR TITLE
Sfml

### PR DESCRIPTION
**Pull request by cnlohr**
I'm still a novice here.  I'm trying to figure out how to merge everything back to master.

### CODE REVIEW

**Comment by phiresky** [comment]
Oh god this won't go well. With the merged and reverted other pull request this will probably do weird stuff.

**Comment by phiresky** [comment]
nope, that didn't work

**Comment by cnlohr** [comment]
GAAAAHHH It's on fire!

**Comment by cnlohr** [comment]
Only thing I can think to do now is try to overwrite the other changes in main with the SFML branch?

**Pull request merged**
