### PR TITLE
tcc_relocate now has different syntax.

### PR DESCRIPTION
**Pull request by ArchimedesPi**
Fix so that it compiles.

### CODE REVIEW

**Comment by ArchimedesPi** [comment]
@cnlohr I'm not exactly sure why I had to do this to get it to compile, any ideas?

**Comment by cnlohr** [comment]
This doesn't actually work.  I am not sure what's going on now, but, if I do this, it doesn't seem to find triggers sometimes.

Perhaps your problem is related to this: https://lists.gnu.org/archive/html/tinycc-devel/2012-08/msg00027.html ?

**Comment by cnlohr** [comment]
(I'm not merging this just yet)

**Comment by ArchimedesPi** [comment]
Just to let you know, my computer has a pretty messed up enviroment.
I'll be trying to get it to compile on my new computer, don't have high
hopes it'll run well on laptop integrated graphics.
Perhaps the "correct" fix is to, as per the link you gave, *`#define
TCC_RELOCATE_AUTO (void*)1`*
I can patch the PR to do that.

**Comment by cnlohr** [comment]
I can't tell is there any way of doing that with a new merge request?  Does that different define fix your problem?

**Comment by ArchimedesPi** [comment]
Heh, sorry :)
This was caused by my having TCC 0.9.25 instead of 0.9.26.
Tried building with the latest version and it's all OK :)

**Pull request closed without merging**
